# ====================================================================
# GENERATED by scripts/generate_bindings.cr — DO NOT EDIT.
# Source: wgpu-native v29.0.0.0 (webgpu.h)
# Regenerate: crystal run scripts/generate_bindings.cr
# ====================================================================
require "./link"

lib LibWGPU
  alias Bool = UInt32
  alias Flags = UInt64
  alias ProcFn = -> Void

  # --- Opaque handles ---
  type Adapter = Void*
  type BindGroup = Void*
  type BindGroupLayout = Void*
  type Buffer = Void*
  type CommandBuffer = Void*
  type CommandEncoder = Void*
  type ComputePassEncoder = Void*
  type ComputePipeline = Void*
  type Device = Void*
  type ExternalTexture = Void*
  type Instance = Void*
  type PipelineLayout = Void*
  type QuerySet = Void*
  type Queue = Void*
  type RenderBundle = Void*
  type RenderBundleEncoder = Void*
  type RenderPassEncoder = Void*
  type RenderPipeline = Void*
  type Sampler = Void*
  type ShaderModule = Void*
  type Surface = Void*
  type Texture = Void*
  type TextureView = Void*

  # --- Enums ---
  enum AdapterType
    DiscreteGPU   = 0x00000001
    IntegratedGPU = 0x00000002
    CPU           = 0x00000003
    Unknown       = 0x00000004
    Force32       = 0x7FFFFFFF
  end

  enum AddressMode
    Undefined    = 0x00000000
    ClampToEdge  = 0x00000001
    Repeat       = 0x00000002
    MirrorRepeat = 0x00000003
    Force32      = 0x7FFFFFFF
  end

  enum BackendType
    Undefined = 0x00000000
    Null      = 0x00000001
    WebGPU    = 0x00000002
    D3D11     = 0x00000003
    D3D12     = 0x00000004
    Metal     = 0x00000005
    Vulkan    = 0x00000006
    OpenGL    = 0x00000007
    OpenGLES  = 0x00000008
    Force32   = 0x7FFFFFFF
  end

  enum BlendFactor
    Undefined         = 0x00000000
    Zero              = 0x00000001
    One               = 0x00000002
    Src               = 0x00000003
    OneMinusSrc       = 0x00000004
    SrcAlpha          = 0x00000005
    OneMinusSrcAlpha  = 0x00000006
    Dst               = 0x00000007
    OneMinusDst       = 0x00000008
    DstAlpha          = 0x00000009
    OneMinusDstAlpha  = 0x0000000A
    SrcAlphaSaturated = 0x0000000B
    Constant          = 0x0000000C
    OneMinusConstant  = 0x0000000D
    Src1              = 0x0000000E
    OneMinusSrc1      = 0x0000000F
    Src1Alpha         = 0x00000010
    OneMinusSrc1Alpha = 0x00000011
    Force32           = 0x7FFFFFFF
  end

  enum BlendOperation
    Undefined       = 0x00000000
    Add             = 0x00000001
    Subtract        = 0x00000002
    ReverseSubtract = 0x00000003
    Min             = 0x00000004
    Max             = 0x00000005
    Force32         = 0x7FFFFFFF
  end

  enum BufferBindingType
    BindingNotUsed  = 0x00000000
    Undefined       = 0x00000001
    Uniform         = 0x00000002
    Storage         = 0x00000003
    ReadOnlyStorage = 0x00000004
    Force32         = 0x7FFFFFFF
  end

  enum BufferMapState
    Unmapped = 0x00000001
    Pending  = 0x00000002
    Mapped   = 0x00000003
    Force32  = 0x7FFFFFFF
  end

  enum CallbackMode
    WaitAnyOnly        = 0x00000001
    AllowProcessEvents = 0x00000002
    AllowSpontaneous   = 0x00000003
    Force32            = 0x7FFFFFFF
  end

  enum CompareFunction
    Undefined    = 0x00000000
    Never        = 0x00000001
    Less         = 0x00000002
    Equal        = 0x00000003
    LessEqual    = 0x00000004
    Greater      = 0x00000005
    NotEqual     = 0x00000006
    GreaterEqual = 0x00000007
    Always       = 0x00000008
    Force32      = 0x7FFFFFFF
  end

  enum CompilationInfoRequestStatus
    Success           = 0x00000001
    CallbackCancelled = 0x00000002
    Force32           = 0x7FFFFFFF
  end

  enum CompilationMessageType
    Error   = 0x00000001
    Warning = 0x00000002
    Info    = 0x00000003
    Force32 = 0x7FFFFFFF
  end

  enum ComponentSwizzle
    Undefined = 0x00000000
    Zero      = 0x00000001
    One       = 0x00000002
    R         = 0x00000003
    G         = 0x00000004
    B         = 0x00000005
    A         = 0x00000006
    Force32   = 0x7FFFFFFF
  end

  enum CompositeAlphaMode
    Auto            = 0x00000000
    Opaque          = 0x00000001
    Premultiplied   = 0x00000002
    Unpremultiplied = 0x00000003
    Inherit         = 0x00000004
    Force32         = 0x7FFFFFFF
  end

  enum CreatePipelineAsyncStatus
    Success           = 0x00000001
    CallbackCancelled = 0x00000002
    ValidationError   = 0x00000003
    InternalError     = 0x00000004
    Force32           = 0x7FFFFFFF
  end

  enum CullMode
    Undefined = 0x00000000
    None      = 0x00000001
    Front     = 0x00000002
    Back      = 0x00000003
    Force32   = 0x7FFFFFFF
  end

  enum DeviceLostReason
    Unknown           = 0x00000001
    Destroyed         = 0x00000002
    CallbackCancelled = 0x00000003
    FailedCreation    = 0x00000004
    Force32           = 0x7FFFFFFF
  end

  enum ErrorFilter
    Validation  = 0x00000001
    OutOfMemory = 0x00000002
    Internal    = 0x00000003
    Force32     = 0x7FFFFFFF
  end

  enum ErrorType
    NoError     = 0x00000001
    Validation  = 0x00000002
    OutOfMemory = 0x00000003
    Internal    = 0x00000004
    Unknown     = 0x00000005
    Force32     = 0x7FFFFFFF
  end

  enum FeatureLevel
    Undefined     = 0x00000000
    Compatibility = 0x00000001
    Core          = 0x00000002
    Force32       = 0x7FFFFFFF
  end

  enum FeatureName
    CoreFeaturesAndLimits          = 0x00000001
    DepthClipControl               = 0x00000002
    Depth32FloatStencil8           = 0x00000003
    TextureCompressionBC           = 0x00000004
    TextureCompressionBCSliced3D   = 0x00000005
    TextureCompressionETC2         = 0x00000006
    TextureCompressionASTC         = 0x00000007
    TextureCompressionASTCSliced3D = 0x00000008
    TimestampQuery                 = 0x00000009
    IndirectFirstInstance          = 0x0000000A
    ShaderF16                      = 0x0000000B
    RG11B10UfloatRenderable        = 0x0000000C
    BGRA8UnormStorage              = 0x0000000D
    Float32Filterable              = 0x0000000E
    Float32Blendable               = 0x0000000F
    ClipDistances                  = 0x00000010
    DualSourceBlending             = 0x00000011
    Subgroups                      = 0x00000012
    TextureFormatsTier1            = 0x00000013
    TextureFormatsTier2            = 0x00000014
    PrimitiveIndex                 = 0x00000015
    TextureComponentSwizzle        = 0x00000016
    Force32                        = 0x7FFFFFFF
  end

  enum FilterMode
    Undefined = 0x00000000
    Nearest   = 0x00000001
    Linear    = 0x00000002
    Force32   = 0x7FFFFFFF
  end

  enum FrontFace
    Undefined = 0x00000000
    CCW       = 0x00000001
    CW        = 0x00000002
    Force32   = 0x7FFFFFFF
  end

  enum IndexFormat
    Undefined = 0x00000000
    Uint16    = 0x00000001
    Uint32    = 0x00000002
    Force32   = 0x7FFFFFFF
  end

  enum InstanceFeatureName
    TimedWaitAny              = 0x00000001
    ShaderSourceSPIRV         = 0x00000002
    MultipleDevicesPerAdapter = 0x00000003
    Force32                   = 0x7FFFFFFF
  end

  enum LoadOp
    Undefined = 0x00000000
    Load      = 0x00000001
    Clear     = 0x00000002
    Force32   = 0x7FFFFFFF
  end

  enum MapAsyncStatus
    Success           = 0x00000001
    CallbackCancelled = 0x00000002
    Error             = 0x00000003
    Aborted           = 0x00000004
    Force32           = 0x7FFFFFFF
  end

  enum MipmapFilterMode
    Undefined = 0x00000000
    Nearest   = 0x00000001
    Linear    = 0x00000002
    Force32   = 0x7FFFFFFF
  end

  enum OptionalBool
    False     = 0x00000000
    True      = 0x00000001
    Undefined = 0x00000002
    Force32   = 0x7FFFFFFF
  end

  enum PopErrorScopeStatus
    Success           = 0x00000001
    CallbackCancelled = 0x00000002
    Error             = 0x00000003
    Force32           = 0x7FFFFFFF
  end

  enum PowerPreference
    Undefined       = 0x00000000
    LowPower        = 0x00000001
    HighPerformance = 0x00000002
    Force32         = 0x7FFFFFFF
  end

  enum PredefinedColorSpace
    SRGB      = 0x00000001
    DisplayP3 = 0x00000002
    Force32   = 0x7FFFFFFF
  end

  enum PresentMode
    Undefined   = 0x00000000
    Fifo        = 0x00000001
    FifoRelaxed = 0x00000002
    Immediate   = 0x00000003
    Mailbox     = 0x00000004
    Force32     = 0x7FFFFFFF
  end

  enum PrimitiveTopology
    Undefined     = 0x00000000
    PointList     = 0x00000001
    LineList      = 0x00000002
    LineStrip     = 0x00000003
    TriangleList  = 0x00000004
    TriangleStrip = 0x00000005
    Force32       = 0x7FFFFFFF
  end

  enum QueryType
    Occlusion = 0x00000001
    Timestamp = 0x00000002
    Force32   = 0x7FFFFFFF
  end

  enum QueueWorkDoneStatus
    Success           = 0x00000001
    CallbackCancelled = 0x00000002
    Error             = 0x00000003
    Force32           = 0x7FFFFFFF
  end

  enum RequestAdapterStatus
    Success           = 0x00000001
    CallbackCancelled = 0x00000002
    Unavailable       = 0x00000003
    Error             = 0x00000004
    Force32           = 0x7FFFFFFF
  end

  enum RequestDeviceStatus
    Success           = 0x00000001
    CallbackCancelled = 0x00000002
    Error             = 0x00000003
    Force32           = 0x7FFFFFFF
  end

  enum SamplerBindingType
    BindingNotUsed = 0x00000000
    Undefined      = 0x00000001
    Filtering      = 0x00000002
    NonFiltering   = 0x00000003
    Comparison     = 0x00000004
    Force32        = 0x7FFFFFFF
  end

  enum Status
    Success = 0x00000001
    Error   = 0x00000002
    Force32 = 0x7FFFFFFF
  end

  enum StencilOperation
    Undefined      = 0x00000000
    Keep           = 0x00000001
    Zero           = 0x00000002
    Replace        = 0x00000003
    Invert         = 0x00000004
    IncrementClamp = 0x00000005
    DecrementClamp = 0x00000006
    IncrementWrap  = 0x00000007
    DecrementWrap  = 0x00000008
    Force32        = 0x7FFFFFFF
  end

  enum StorageTextureAccess
    BindingNotUsed = 0x00000000
    Undefined      = 0x00000001
    WriteOnly      = 0x00000002
    ReadOnly       = 0x00000003
    ReadWrite      = 0x00000004
    Force32        = 0x7FFFFFFF
  end

  enum StoreOp
    Undefined = 0x00000000
    Store     = 0x00000001
    Discard   = 0x00000002
    Force32   = 0x7FFFFFFF
  end

  enum SType
    ShaderSourceSPIRV                 = 0x00000001
    ShaderSourceWGSL                  = 0x00000002
    RenderPassMaxDrawCount            = 0x00000003
    SurfaceSourceMetalLayer           = 0x00000004
    SurfaceSourceWindowsHWND          = 0x00000005
    SurfaceSourceXlibWindow           = 0x00000006
    SurfaceSourceWaylandSurface       = 0x00000007
    SurfaceSourceAndroidNativeWindow  = 0x00000008
    SurfaceSourceXCBWindow            = 0x00000009
    SurfaceColorManagement            = 0x0000000A
    RequestAdapterWebXROptions        = 0x0000000B
    TextureComponentSwizzleDescriptor = 0x0000000C
    ExternalTextureBindingLayout      = 0x0000000D
    ExternalTextureBindingEntry       = 0x0000000E
    CompatibilityModeLimits           = 0x0000000F
    TextureBindingViewDimension       = 0x00000010
    Force32                           = 0x7FFFFFFF
  end

  enum SurfaceGetCurrentTextureStatus
    SuccessOptimal    = 0x00000001
    SuccessSuboptimal = 0x00000002
    Timeout           = 0x00000003
    Outdated          = 0x00000004
    Lost              = 0x00000005
    Error             = 0x00000006
    Force32           = 0x7FFFFFFF
  end

  enum TextureAspect
    Undefined   = 0x00000000
    All         = 0x00000001
    StencilOnly = 0x00000002
    DepthOnly   = 0x00000003
    Force32     = 0x7FFFFFFF
  end

  enum TextureDimension
    Undefined = 0x00000000
    N1D       = 0x00000001
    N2D       = 0x00000002
    N3D       = 0x00000003
    Force32   = 0x7FFFFFFF
  end

  enum TextureFormat
    Undefined            = 0x00000000
    R8Unorm              = 0x00000001
    R8Snorm              = 0x00000002
    R8Uint               = 0x00000003
    R8Sint               = 0x00000004
    R16Unorm             = 0x00000005
    R16Snorm             = 0x00000006
    R16Uint              = 0x00000007
    R16Sint              = 0x00000008
    R16Float             = 0x00000009
    RG8Unorm             = 0x0000000A
    RG8Snorm             = 0x0000000B
    RG8Uint              = 0x0000000C
    RG8Sint              = 0x0000000D
    R32Float             = 0x0000000E
    R32Uint              = 0x0000000F
    R32Sint              = 0x00000010
    RG16Unorm            = 0x00000011
    RG16Snorm            = 0x00000012
    RG16Uint             = 0x00000013
    RG16Sint             = 0x00000014
    RG16Float            = 0x00000015
    RGBA8Unorm           = 0x00000016
    RGBA8UnormSrgb       = 0x00000017
    RGBA8Snorm           = 0x00000018
    RGBA8Uint            = 0x00000019
    RGBA8Sint            = 0x0000001A
    BGRA8Unorm           = 0x0000001B
    BGRA8UnormSrgb       = 0x0000001C
    RGB10A2Uint          = 0x0000001D
    RGB10A2Unorm         = 0x0000001E
    RG11B10Ufloat        = 0x0000001F
    RGB9E5Ufloat         = 0x00000020
    RG32Float            = 0x00000021
    RG32Uint             = 0x00000022
    RG32Sint             = 0x00000023
    RGBA16Unorm          = 0x00000024
    RGBA16Snorm          = 0x00000025
    RGBA16Uint           = 0x00000026
    RGBA16Sint           = 0x00000027
    RGBA16Float          = 0x00000028
    RGBA32Float          = 0x00000029
    RGBA32Uint           = 0x0000002A
    RGBA32Sint           = 0x0000002B
    Stencil8             = 0x0000002C
    Depth16Unorm         = 0x0000002D
    Depth24Plus          = 0x0000002E
    Depth24PlusStencil8  = 0x0000002F
    Depth32Float         = 0x00000030
    Depth32FloatStencil8 = 0x00000031
    BC1RGBAUnorm         = 0x00000032
    BC1RGBAUnormSrgb     = 0x00000033
    BC2RGBAUnorm         = 0x00000034
    BC2RGBAUnormSrgb     = 0x00000035
    BC3RGBAUnorm         = 0x00000036
    BC3RGBAUnormSrgb     = 0x00000037
    BC4RUnorm            = 0x00000038
    BC4RSnorm            = 0x00000039
    BC5RGUnorm           = 0x0000003A
    BC5RGSnorm           = 0x0000003B
    BC6HRGBUfloat        = 0x0000003C
    BC6HRGBFloat         = 0x0000003D
    BC7RGBAUnorm         = 0x0000003E
    BC7RGBAUnormSrgb     = 0x0000003F
    ETC2RGB8Unorm        = 0x00000040
    ETC2RGB8UnormSrgb    = 0x00000041
    ETC2RGB8A1Unorm      = 0x00000042
    ETC2RGB8A1UnormSrgb  = 0x00000043
    ETC2RGBA8Unorm       = 0x00000044
    ETC2RGBA8UnormSrgb   = 0x00000045
    EACR11Unorm          = 0x00000046
    EACR11Snorm          = 0x00000047
    EACRG11Unorm         = 0x00000048
    EACRG11Snorm         = 0x00000049
    ASTC4x4Unorm         = 0x0000004A
    ASTC4x4UnormSrgb     = 0x0000004B
    ASTC5x4Unorm         = 0x0000004C
    ASTC5x4UnormSrgb     = 0x0000004D
    ASTC5x5Unorm         = 0x0000004E
    ASTC5x5UnormSrgb     = 0x0000004F
    ASTC6x5Unorm         = 0x00000050
    ASTC6x5UnormSrgb     = 0x00000051
    ASTC6x6Unorm         = 0x00000052
    ASTC6x6UnormSrgb     = 0x00000053
    ASTC8x5Unorm         = 0x00000054
    ASTC8x5UnormSrgb     = 0x00000055
    ASTC8x6Unorm         = 0x00000056
    ASTC8x6UnormSrgb     = 0x00000057
    ASTC8x8Unorm         = 0x00000058
    ASTC8x8UnormSrgb     = 0x00000059
    ASTC10x5Unorm        = 0x0000005A
    ASTC10x5UnormSrgb    = 0x0000005B
    ASTC10x6Unorm        = 0x0000005C
    ASTC10x6UnormSrgb    = 0x0000005D
    ASTC10x8Unorm        = 0x0000005E
    ASTC10x8UnormSrgb    = 0x0000005F
    ASTC10x10Unorm       = 0x00000060
    ASTC10x10UnormSrgb   = 0x00000061
    ASTC12x10Unorm       = 0x00000062
    ASTC12x10UnormSrgb   = 0x00000063
    ASTC12x12Unorm       = 0x00000064
    ASTC12x12UnormSrgb   = 0x00000065
    Force32              = 0x7FFFFFFF
  end

  enum TextureSampleType
    BindingNotUsed    = 0x00000000
    Undefined         = 0x00000001
    Float             = 0x00000002
    UnfilterableFloat = 0x00000003
    Depth             = 0x00000004
    Sint              = 0x00000005
    Uint              = 0x00000006
    Force32           = 0x7FFFFFFF
  end

  enum TextureViewDimension
    Undefined = 0x00000000
    N1D       = 0x00000001
    N2D       = 0x00000002
    N2DArray  = 0x00000003
    Cube      = 0x00000004
    CubeArray = 0x00000005
    N3D       = 0x00000006
    Force32   = 0x7FFFFFFF
  end

  enum ToneMappingMode
    Standard = 0x00000001
    Extended = 0x00000002
    Force32  = 0x7FFFFFFF
  end

  enum VertexFormat
    Uint8           = 0x00000001
    Uint8x2         = 0x00000002
    Uint8x4         = 0x00000003
    Sint8           = 0x00000004
    Sint8x2         = 0x00000005
    Sint8x4         = 0x00000006
    Unorm8          = 0x00000007
    Unorm8x2        = 0x00000008
    Unorm8x4        = 0x00000009
    Snorm8          = 0x0000000A
    Snorm8x2        = 0x0000000B
    Snorm8x4        = 0x0000000C
    Uint16          = 0x0000000D
    Uint16x2        = 0x0000000E
    Uint16x4        = 0x0000000F
    Sint16          = 0x00000010
    Sint16x2        = 0x00000011
    Sint16x4        = 0x00000012
    Unorm16         = 0x00000013
    Unorm16x2       = 0x00000014
    Unorm16x4       = 0x00000015
    Snorm16         = 0x00000016
    Snorm16x2       = 0x00000017
    Snorm16x4       = 0x00000018
    Float16         = 0x00000019
    Float16x2       = 0x0000001A
    Float16x4       = 0x0000001B
    Float32         = 0x0000001C
    Float32x2       = 0x0000001D
    Float32x3       = 0x0000001E
    Float32x4       = 0x0000001F
    Uint32          = 0x00000020
    Uint32x2        = 0x00000021
    Uint32x3        = 0x00000022
    Uint32x4        = 0x00000023
    Sint32          = 0x00000024
    Sint32x2        = 0x00000025
    Sint32x3        = 0x00000026
    Sint32x4        = 0x00000027
    Unorm10_10_10_2 = 0x00000028
    Unorm8x4BGRA    = 0x00000029
    Force32         = 0x7FFFFFFF
  end

  enum VertexStepMode
    Undefined = 0x00000000
    Vertex    = 0x00000001
    Instance  = 0x00000002
    Force32   = 0x7FFFFFFF
  end

  enum WaitStatus
    Success  = 0x00000001
    TimedOut = 0x00000002
    Error    = 0x00000003
    Force32  = 0x7FFFFFFF
  end

  enum WGSLLanguageFeatureName
    ReadonlyAndReadwriteStorageTextures = 0x00000001
    Packed4x8IntegerDotProduct          = 0x00000002
    UnrestrictedPointerParameters       = 0x00000003
    PointerCompositeAccess              = 0x00000004
    UniformBufferStandardLayout         = 0x00000005
    SubgroupId                          = 0x00000006
    TextureAndSamplerLet                = 0x00000007
    SubgroupUniformity                  = 0x00000008
    TextureFormatsTier1                 = 0x00000009
    Force32                             = 0x7FFFFFFF
  end

  # --- Bitflags (WGPUFlags = UInt64) ---
  @[Flags]
  enum BufferUsage : UInt64
    None         = 0x0000000000000000
    MapRead      = 0x0000000000000001
    MapWrite     = 0x0000000000000002
    CopySrc      = 0x0000000000000004
    CopyDst      = 0x0000000000000008
    Index        = 0x0000000000000010
    Vertex       = 0x0000000000000020
    Uniform      = 0x0000000000000040
    Storage      = 0x0000000000000080
    Indirect     = 0x0000000000000100
    QueryResolve = 0x0000000000000200
  end

  @[Flags]
  enum ColorWriteMask : UInt64
    None  = 0x0000000000000000
    Red   = 0x0000000000000001
    Green = 0x0000000000000002
    Blue  = 0x0000000000000004
    Alpha = 0x0000000000000008
    All   = 0x000000000000000F
  end

  @[Flags]
  enum MapMode : UInt64
    None  = 0x0000000000000000
    Read  = 0x0000000000000001
    Write = 0x0000000000000002
  end

  @[Flags]
  enum ShaderStage : UInt64
    None     = 0x0000000000000000
    Vertex   = 0x0000000000000001
    Fragment = 0x0000000000000002
    Compute  = 0x0000000000000004
  end

  @[Flags]
  enum TextureUsage : UInt64
    None                = 0x0000000000000000
    CopySrc             = 0x0000000000000001
    CopyDst             = 0x0000000000000002
    TextureBinding      = 0x0000000000000004
    StorageBinding      = 0x0000000000000008
    RenderAttachment    = 0x0000000000000010
    TransientAttachment = 0x0000000000000020
  end

  # --- Callbacks ---
  alias BufferMapCallback = (MapAsyncStatus, StringView, Pointer(Void), Pointer(Void)) -> Void
  alias CompilationInfoCallback = (CompilationInfoRequestStatus, Pointer(CompilationInfo), Pointer(Void), Pointer(Void)) -> Void
  alias CreateComputePipelineAsyncCallback = (CreatePipelineAsyncStatus, ComputePipeline, StringView, Pointer(Void), Pointer(Void)) -> Void
  alias CreateRenderPipelineAsyncCallback = (CreatePipelineAsyncStatus, RenderPipeline, StringView, Pointer(Void), Pointer(Void)) -> Void
  alias DeviceLostCallback = (Pointer(Device), DeviceLostReason, StringView, Pointer(Void), Pointer(Void)) -> Void
  alias PopErrorScopeCallback = (PopErrorScopeStatus, ErrorType, StringView, Pointer(Void), Pointer(Void)) -> Void
  alias QueueWorkDoneCallback = (QueueWorkDoneStatus, StringView, Pointer(Void), Pointer(Void)) -> Void
  alias RequestAdapterCallback = (RequestAdapterStatus, Adapter, StringView, Pointer(Void), Pointer(Void)) -> Void
  alias RequestDeviceCallback = (RequestDeviceStatus, Device, StringView, Pointer(Void), Pointer(Void)) -> Void
  alias UncapturedErrorCallback = (Pointer(Device), ErrorType, StringView, Pointer(Void), Pointer(Void)) -> Void

  # --- Structs ---
  struct StringView
    data : Pointer(LibC::Char)
    length : LibC::SizeT
  end

  struct ChainedStruct
    next_ : Pointer(ChainedStruct)
    s_type : SType
  end

  struct BufferMapCallbackInfo
    next_in_chain : Pointer(ChainedStruct)
    mode : CallbackMode
    callback : BufferMapCallback
    userdata1 : Pointer(Void)
    userdata2 : Pointer(Void)
  end

  struct CompilationInfoCallbackInfo
    next_in_chain : Pointer(ChainedStruct)
    mode : CallbackMode
    callback : CompilationInfoCallback
    userdata1 : Pointer(Void)
    userdata2 : Pointer(Void)
  end

  struct CreateComputePipelineAsyncCallbackInfo
    next_in_chain : Pointer(ChainedStruct)
    mode : CallbackMode
    callback : CreateComputePipelineAsyncCallback
    userdata1 : Pointer(Void)
    userdata2 : Pointer(Void)
  end

  struct CreateRenderPipelineAsyncCallbackInfo
    next_in_chain : Pointer(ChainedStruct)
    mode : CallbackMode
    callback : CreateRenderPipelineAsyncCallback
    userdata1 : Pointer(Void)
    userdata2 : Pointer(Void)
  end

  struct DeviceLostCallbackInfo
    next_in_chain : Pointer(ChainedStruct)
    mode : CallbackMode
    callback : DeviceLostCallback
    userdata1 : Pointer(Void)
    userdata2 : Pointer(Void)
  end

  struct PopErrorScopeCallbackInfo
    next_in_chain : Pointer(ChainedStruct)
    mode : CallbackMode
    callback : PopErrorScopeCallback
    userdata1 : Pointer(Void)
    userdata2 : Pointer(Void)
  end

  struct QueueWorkDoneCallbackInfo
    next_in_chain : Pointer(ChainedStruct)
    mode : CallbackMode
    callback : QueueWorkDoneCallback
    userdata1 : Pointer(Void)
    userdata2 : Pointer(Void)
  end

  struct RequestAdapterCallbackInfo
    next_in_chain : Pointer(ChainedStruct)
    mode : CallbackMode
    callback : RequestAdapterCallback
    userdata1 : Pointer(Void)
    userdata2 : Pointer(Void)
  end

  struct RequestDeviceCallbackInfo
    next_in_chain : Pointer(ChainedStruct)
    mode : CallbackMode
    callback : RequestDeviceCallback
    userdata1 : Pointer(Void)
    userdata2 : Pointer(Void)
  end

  struct UncapturedErrorCallbackInfo
    next_in_chain : Pointer(ChainedStruct)
    callback : UncapturedErrorCallback
    userdata1 : Pointer(Void)
    userdata2 : Pointer(Void)
  end

  struct AdapterInfo
    next_in_chain : Pointer(ChainedStruct)
    vendor : StringView
    architecture : StringView
    device : StringView
    description : StringView
    backend_type : BackendType
    adapter_type : AdapterType
    vendor_id : UInt32
    device_id : UInt32
    subgroup_min_size : UInt32
    subgroup_max_size : UInt32
  end

  struct BlendComponent
    operation : BlendOperation
    src_factor : BlendFactor
    dst_factor : BlendFactor
  end

  struct BufferBindingLayout
    next_in_chain : Pointer(ChainedStruct)
    type_ : BufferBindingType
    has_dynamic_offset : Bool
    min_binding_size : UInt64
  end

  struct BufferDescriptor
    next_in_chain : Pointer(ChainedStruct)
    label : StringView
    usage : BufferUsage
    size : UInt64
    mapped_at_creation : Bool
  end

  struct Color
    r : Float64
    g : Float64
    b : Float64
    a : Float64
  end

  struct CommandBufferDescriptor
    next_in_chain : Pointer(ChainedStruct)
    label : StringView
  end

  struct CommandEncoderDescriptor
    next_in_chain : Pointer(ChainedStruct)
    label : StringView
  end

  struct CompatibilityModeLimits
    chain : ChainedStruct
    max_storage_buffers_in_vertex_stage : UInt32
    max_storage_textures_in_vertex_stage : UInt32
    max_storage_buffers_in_fragment_stage : UInt32
    max_storage_textures_in_fragment_stage : UInt32
  end

  struct CompilationMessage
    next_in_chain : Pointer(ChainedStruct)
    message : StringView
    type_ : CompilationMessageType
    line_num : UInt64
    line_pos : UInt64
    offset : UInt64
    length : UInt64
  end

  struct ConstantEntry
    next_in_chain : Pointer(ChainedStruct)
    key : StringView
    value : Float64
  end

  struct Extent3D
    width : UInt32
    height : UInt32
    depth_or_array_layers : UInt32
  end

  struct ExternalTextureBindingEntry
    chain : ChainedStruct
    external_texture : ExternalTexture
  end

  struct ExternalTextureBindingLayout
    chain : ChainedStruct
  end

  struct Future
    id : UInt64
  end

  struct InstanceLimits
    next_in_chain : Pointer(ChainedStruct)
    timed_wait_any_max_count : LibC::SizeT
  end

  struct MultisampleState
    next_in_chain : Pointer(ChainedStruct)
    count : UInt32
    mask : UInt32
    alpha_to_coverage_enabled : Bool
  end

  struct Origin3D
    x : UInt32
    y : UInt32
    z : UInt32
  end

  struct PassTimestampWrites
    next_in_chain : Pointer(ChainedStruct)
    query_set : QuerySet
    beginning_of_pass_write_index : UInt32
    end_of_pass_write_index : UInt32
  end

  struct PipelineLayoutDescriptor
    next_in_chain : Pointer(ChainedStruct)
    label : StringView
    bind_group_layout_count : LibC::SizeT
    bind_group_layouts : Pointer(BindGroupLayout)
    immediate_size : UInt32
  end

  struct PrimitiveState
    next_in_chain : Pointer(ChainedStruct)
    topology : PrimitiveTopology
    strip_index_format : IndexFormat
    front_face : FrontFace
    cull_mode : CullMode
    unclipped_depth : Bool
  end

  struct QuerySetDescriptor
    next_in_chain : Pointer(ChainedStruct)
    label : StringView
    type_ : QueryType
    count : UInt32
  end

  struct QueueDescriptor
    next_in_chain : Pointer(ChainedStruct)
    label : StringView
  end

  struct RenderBundleDescriptor
    next_in_chain : Pointer(ChainedStruct)
    label : StringView
  end

  struct RenderBundleEncoderDescriptor
    next_in_chain : Pointer(ChainedStruct)
    label : StringView
    color_format_count : LibC::SizeT
    color_formats : Pointer(TextureFormat)
    depth_stencil_format : TextureFormat
    sample_count : UInt32
    depth_read_only : Bool
    stencil_read_only : Bool
  end

  struct RenderPassDepthStencilAttachment
    next_in_chain : Pointer(ChainedStruct)
    view : TextureView
    depth_load_op : LoadOp
    depth_store_op : StoreOp
    depth_clear_value : Float32
    depth_read_only : Bool
    stencil_load_op : LoadOp
    stencil_store_op : StoreOp
    stencil_clear_value : UInt32
    stencil_read_only : Bool
  end

  struct RenderPassMaxDrawCount
    chain : ChainedStruct
    max_draw_count : UInt64
  end

  struct RequestAdapterWebXROptions
    chain : ChainedStruct
    xr_compatible : Bool
  end

  struct SamplerBindingLayout
    next_in_chain : Pointer(ChainedStruct)
    type_ : SamplerBindingType
  end

  struct SamplerDescriptor
    next_in_chain : Pointer(ChainedStruct)
    label : StringView
    address_mode_u : AddressMode
    address_mode_v : AddressMode
    address_mode_w : AddressMode
    mag_filter : FilterMode
    min_filter : FilterMode
    mipmap_filter : MipmapFilterMode
    lod_min_clamp : Float32
    lod_max_clamp : Float32
    compare : CompareFunction
    max_anisotropy : UInt16
  end

  struct ShaderSourceSPIRV
    chain : ChainedStruct
    code_size : UInt32
    code : Pointer(UInt32)
  end

  struct ShaderSourceWGSL
    chain : ChainedStruct
    code : StringView
  end

  struct StencilFaceState
    compare : CompareFunction
    fail_op : StencilOperation
    depth_fail_op : StencilOperation
    pass_op : StencilOperation
  end

  struct StorageTextureBindingLayout
    next_in_chain : Pointer(ChainedStruct)
    access : StorageTextureAccess
    format : TextureFormat
    view_dimension : TextureViewDimension
  end

  struct SupportedFeatures
    feature_count : LibC::SizeT
    features : Pointer(FeatureName)
  end

  struct SupportedInstanceFeatures
    feature_count : LibC::SizeT
    features : Pointer(InstanceFeatureName)
  end

  struct SupportedWGSLLanguageFeatures
    feature_count : LibC::SizeT
    features : Pointer(WGSLLanguageFeatureName)
  end

  struct SurfaceCapabilities
    next_in_chain : Pointer(ChainedStruct)
    usages : TextureUsage
    format_count : LibC::SizeT
    formats : Pointer(TextureFormat)
    present_mode_count : LibC::SizeT
    present_modes : Pointer(PresentMode)
    alpha_mode_count : LibC::SizeT
    alpha_modes : Pointer(CompositeAlphaMode)
  end

  struct SurfaceColorManagement
    chain : ChainedStruct
    color_space : PredefinedColorSpace
    tone_mapping_mode : ToneMappingMode
  end

  struct SurfaceConfiguration
    next_in_chain : Pointer(ChainedStruct)
    device : Device
    format : TextureFormat
    usage : TextureUsage
    width : UInt32
    height : UInt32
    view_format_count : LibC::SizeT
    view_formats : Pointer(TextureFormat)
    alpha_mode : CompositeAlphaMode
    present_mode : PresentMode
  end

  struct SurfaceSourceAndroidNativeWindow
    chain : ChainedStruct
    window : Pointer(Void)
  end

  struct SurfaceSourceMetalLayer
    chain : ChainedStruct
    layer : Pointer(Void)
  end

  struct SurfaceSourceWaylandSurface
    chain : ChainedStruct
    display : Pointer(Void)
    surface : Pointer(Void)
  end

  struct SurfaceSourceWindowsHWND
    chain : ChainedStruct
    hinstance : Pointer(Void)
    hwnd : Pointer(Void)
  end

  struct SurfaceSourceXCBWindow
    chain : ChainedStruct
    connection : Pointer(Void)
    window : UInt32
  end

  struct SurfaceSourceXlibWindow
    chain : ChainedStruct
    display : Pointer(Void)
    window : UInt64
  end

  struct SurfaceTexture
    next_in_chain : Pointer(ChainedStruct)
    texture : Texture
    status : SurfaceGetCurrentTextureStatus
  end

  struct TexelCopyBufferLayout
    offset : UInt64
    bytes_per_row : UInt32
    rows_per_image : UInt32
  end

  struct TextureBindingLayout
    next_in_chain : Pointer(ChainedStruct)
    sample_type : TextureSampleType
    view_dimension : TextureViewDimension
    multisampled : Bool
  end

  struct TextureBindingViewDimension
    chain : ChainedStruct
    texture_binding_view_dimension : TextureViewDimension
  end

  struct TextureComponentSwizzle
    r : ComponentSwizzle
    g : ComponentSwizzle
    b : ComponentSwizzle
    a : ComponentSwizzle
  end

  struct VertexAttribute
    next_in_chain : Pointer(ChainedStruct)
    format : VertexFormat
    offset : UInt64
    shader_location : UInt32
  end

  struct BindGroupEntry
    next_in_chain : Pointer(ChainedStruct)
    binding : UInt32
    buffer : Buffer
    offset : UInt64
    size : UInt64
    sampler : Sampler
    texture_view : TextureView
  end

  struct BindGroupLayoutEntry
    next_in_chain : Pointer(ChainedStruct)
    binding : UInt32
    visibility : ShaderStage
    binding_array_size : UInt32
    buffer : BufferBindingLayout
    sampler : SamplerBindingLayout
    texture : TextureBindingLayout
    storage_texture : StorageTextureBindingLayout
  end

  struct BlendState
    color : BlendComponent
    alpha : BlendComponent
  end

  struct CompilationInfo
    next_in_chain : Pointer(ChainedStruct)
    message_count : LibC::SizeT
    messages : Pointer(CompilationMessage)
  end

  struct ComputePassDescriptor
    next_in_chain : Pointer(ChainedStruct)
    label : StringView
    timestamp_writes : Pointer(PassTimestampWrites)
  end

  struct ComputeState
    next_in_chain : Pointer(ChainedStruct)
    module_ : ShaderModule
    entry_point : StringView
    constant_count : LibC::SizeT
    constants : Pointer(ConstantEntry)
  end

  struct DepthStencilState
    next_in_chain : Pointer(ChainedStruct)
    format : TextureFormat
    depth_write_enabled : OptionalBool
    depth_compare : CompareFunction
    stencil_front : StencilFaceState
    stencil_back : StencilFaceState
    stencil_read_mask : UInt32
    stencil_write_mask : UInt32
    depth_bias : Int32
    depth_bias_slope_scale : Float32
    depth_bias_clamp : Float32
  end

  struct FutureWaitInfo
    future : Future
    completed : Bool
  end

  struct InstanceDescriptor
    next_in_chain : Pointer(ChainedStruct)
    required_feature_count : LibC::SizeT
    required_features : Pointer(InstanceFeatureName)
    required_limits : Pointer(InstanceLimits)
  end

  struct Limits
    next_in_chain : Pointer(ChainedStruct)
    max_texture_dimension1_d : UInt32
    max_texture_dimension2_d : UInt32
    max_texture_dimension3_d : UInt32
    max_texture_array_layers : UInt32
    max_bind_groups : UInt32
    max_bind_groups_plus_vertex_buffers : UInt32
    max_bindings_per_bind_group : UInt32
    max_dynamic_uniform_buffers_per_pipeline_layout : UInt32
    max_dynamic_storage_buffers_per_pipeline_layout : UInt32
    max_sampled_textures_per_shader_stage : UInt32
    max_samplers_per_shader_stage : UInt32
    max_storage_buffers_per_shader_stage : UInt32
    max_storage_textures_per_shader_stage : UInt32
    max_uniform_buffers_per_shader_stage : UInt32
    max_uniform_buffer_binding_size : UInt64
    max_storage_buffer_binding_size : UInt64
    min_uniform_buffer_offset_alignment : UInt32
    min_storage_buffer_offset_alignment : UInt32
    max_vertex_buffers : UInt32
    max_buffer_size : UInt64
    max_vertex_attributes : UInt32
    max_vertex_buffer_array_stride : UInt32
    max_inter_stage_shader_variables : UInt32
    max_color_attachments : UInt32
    max_color_attachment_bytes_per_sample : UInt32
    max_compute_workgroup_storage_size : UInt32
    max_compute_invocations_per_workgroup : UInt32
    max_compute_workgroup_size_x : UInt32
    max_compute_workgroup_size_y : UInt32
    max_compute_workgroup_size_z : UInt32
    max_compute_workgroups_per_dimension : UInt32
    max_immediate_size : UInt32
  end

  struct RenderPassColorAttachment
    next_in_chain : Pointer(ChainedStruct)
    view : TextureView
    depth_slice : UInt32
    resolve_target : TextureView
    load_op : LoadOp
    store_op : StoreOp
    clear_value : Color
  end

  struct RequestAdapterOptions
    next_in_chain : Pointer(ChainedStruct)
    feature_level : FeatureLevel
    power_preference : PowerPreference
    force_fallback_adapter : Bool
    backend_type : BackendType
    compatible_surface : Surface
  end

  struct ShaderModuleDescriptor
    next_in_chain : Pointer(ChainedStruct)
    label : StringView
  end

  struct SurfaceDescriptor
    next_in_chain : Pointer(ChainedStruct)
    label : StringView
  end

  struct TexelCopyBufferInfo
    layout : TexelCopyBufferLayout
    buffer : Buffer
  end

  struct TexelCopyTextureInfo
    texture : Texture
    mip_level : UInt32
    origin : Origin3D
    aspect : TextureAspect
  end

  struct TextureComponentSwizzleDescriptor
    chain : ChainedStruct
    swizzle : TextureComponentSwizzle
  end

  struct TextureDescriptor
    next_in_chain : Pointer(ChainedStruct)
    label : StringView
    usage : TextureUsage
    dimension : TextureDimension
    size : Extent3D
    format : TextureFormat
    mip_level_count : UInt32
    sample_count : UInt32
    view_format_count : LibC::SizeT
    view_formats : Pointer(TextureFormat)
  end

  struct VertexBufferLayout
    next_in_chain : Pointer(ChainedStruct)
    step_mode : VertexStepMode
    array_stride : UInt64
    attribute_count : LibC::SizeT
    attributes : Pointer(VertexAttribute)
  end

  struct BindGroupDescriptor
    next_in_chain : Pointer(ChainedStruct)
    label : StringView
    layout : BindGroupLayout
    entry_count : LibC::SizeT
    entries : Pointer(BindGroupEntry)
  end

  struct BindGroupLayoutDescriptor
    next_in_chain : Pointer(ChainedStruct)
    label : StringView
    entry_count : LibC::SizeT
    entries : Pointer(BindGroupLayoutEntry)
  end

  struct ColorTargetState
    next_in_chain : Pointer(ChainedStruct)
    format : TextureFormat
    blend : Pointer(BlendState)
    write_mask : ColorWriteMask
  end

  struct ComputePipelineDescriptor
    next_in_chain : Pointer(ChainedStruct)
    label : StringView
    layout : PipelineLayout
    compute : ComputeState
  end

  struct DeviceDescriptor
    next_in_chain : Pointer(ChainedStruct)
    label : StringView
    required_feature_count : LibC::SizeT
    required_features : Pointer(FeatureName)
    required_limits : Pointer(Limits)
    default_queue : QueueDescriptor
    device_lost_callback_info : DeviceLostCallbackInfo
    uncaptured_error_callback_info : UncapturedErrorCallbackInfo
  end

  struct RenderPassDescriptor
    next_in_chain : Pointer(ChainedStruct)
    label : StringView
    color_attachment_count : LibC::SizeT
    color_attachments : Pointer(RenderPassColorAttachment)
    depth_stencil_attachment : Pointer(RenderPassDepthStencilAttachment)
    occlusion_query_set : QuerySet
    timestamp_writes : Pointer(PassTimestampWrites)
  end

  struct TextureViewDescriptor
    next_in_chain : Pointer(ChainedStruct)
    label : StringView
    format : TextureFormat
    dimension : TextureViewDimension
    base_mip_level : UInt32
    mip_level_count : UInt32
    base_array_layer : UInt32
    array_layer_count : UInt32
    aspect : TextureAspect
    usage : TextureUsage
  end

  struct VertexState
    next_in_chain : Pointer(ChainedStruct)
    module_ : ShaderModule
    entry_point : StringView
    constant_count : LibC::SizeT
    constants : Pointer(ConstantEntry)
    buffer_count : LibC::SizeT
    buffers : Pointer(VertexBufferLayout)
  end

  struct FragmentState
    next_in_chain : Pointer(ChainedStruct)
    module_ : ShaderModule
    entry_point : StringView
    constant_count : LibC::SizeT
    constants : Pointer(ConstantEntry)
    target_count : LibC::SizeT
    targets : Pointer(ColorTargetState)
  end

  struct RenderPipelineDescriptor
    next_in_chain : Pointer(ChainedStruct)
    label : StringView
    layout : PipelineLayout
    vertex : VertexState
    primitive : PrimitiveState
    depth_stencil : Pointer(DepthStencilState)
    multisample : MultisampleState
    fragment : Pointer(FragmentState)
  end

  # --- Functions ---
  fun create_instance = wgpuCreateInstance(Pointer(InstanceDescriptor)) : Instance
  fun get_instance_features = wgpuGetInstanceFeatures(Pointer(SupportedInstanceFeatures)) : Void
  fun get_instance_limits = wgpuGetInstanceLimits(Pointer(InstanceLimits)) : Status
  fun has_instance_feature = wgpuHasInstanceFeature(InstanceFeatureName) : Bool
  fun get_proc_address = wgpuGetProcAddress(StringView) : ProcFn
  fun adapter_get_features = wgpuAdapterGetFeatures(Adapter, Pointer(SupportedFeatures)) : Void
  fun adapter_get_info = wgpuAdapterGetInfo(Adapter, Pointer(AdapterInfo)) : Status
  fun adapter_get_limits = wgpuAdapterGetLimits(Adapter, Pointer(Limits)) : Status
  fun adapter_has_feature = wgpuAdapterHasFeature(Adapter, FeatureName) : Bool
  fun adapter_request_device = wgpuAdapterRequestDevice(Adapter, Pointer(DeviceDescriptor), RequestDeviceCallbackInfo) : Future
  fun adapter_add_ref = wgpuAdapterAddRef(Adapter) : Void
  fun adapter_release = wgpuAdapterRelease(Adapter) : Void
  fun adapter_info_free_members = wgpuAdapterInfoFreeMembers(AdapterInfo) : Void
  fun bind_group_set_label = wgpuBindGroupSetLabel(BindGroup, StringView) : Void
  fun bind_group_add_ref = wgpuBindGroupAddRef(BindGroup) : Void
  fun bind_group_release = wgpuBindGroupRelease(BindGroup) : Void
  fun bind_group_layout_set_label = wgpuBindGroupLayoutSetLabel(BindGroupLayout, StringView) : Void
  fun bind_group_layout_add_ref = wgpuBindGroupLayoutAddRef(BindGroupLayout) : Void
  fun bind_group_layout_release = wgpuBindGroupLayoutRelease(BindGroupLayout) : Void
  fun buffer_destroy = wgpuBufferDestroy(Buffer) : Void
  fun buffer_get_const_mapped_range = wgpuBufferGetConstMappedRange(Buffer, LibC::SizeT, LibC::SizeT) : Pointer(Void)
  fun buffer_get_mapped_range = wgpuBufferGetMappedRange(Buffer, LibC::SizeT, LibC::SizeT) : Pointer(Void)
  fun buffer_get_map_state = wgpuBufferGetMapState(Buffer) : BufferMapState
  fun buffer_get_size = wgpuBufferGetSize(Buffer) : UInt64
  fun buffer_get_usage = wgpuBufferGetUsage(Buffer) : BufferUsage
  fun buffer_map_async = wgpuBufferMapAsync(Buffer, MapMode, LibC::SizeT, LibC::SizeT, BufferMapCallbackInfo) : Future
  fun buffer_read_mapped_range = wgpuBufferReadMappedRange(Buffer, LibC::SizeT, Pointer(Void), LibC::SizeT) : Status
  fun buffer_set_label = wgpuBufferSetLabel(Buffer, StringView) : Void
  fun buffer_unmap = wgpuBufferUnmap(Buffer) : Void
  fun buffer_write_mapped_range = wgpuBufferWriteMappedRange(Buffer, LibC::SizeT, Pointer(Void), LibC::SizeT) : Status
  fun buffer_add_ref = wgpuBufferAddRef(Buffer) : Void
  fun buffer_release = wgpuBufferRelease(Buffer) : Void
  fun command_buffer_set_label = wgpuCommandBufferSetLabel(CommandBuffer, StringView) : Void
  fun command_buffer_add_ref = wgpuCommandBufferAddRef(CommandBuffer) : Void
  fun command_buffer_release = wgpuCommandBufferRelease(CommandBuffer) : Void
  fun command_encoder_begin_compute_pass = wgpuCommandEncoderBeginComputePass(CommandEncoder, Pointer(ComputePassDescriptor)) : ComputePassEncoder
  fun command_encoder_begin_render_pass = wgpuCommandEncoderBeginRenderPass(CommandEncoder, Pointer(RenderPassDescriptor)) : RenderPassEncoder
  fun command_encoder_clear_buffer = wgpuCommandEncoderClearBuffer(CommandEncoder, Buffer, UInt64, UInt64) : Void
  fun command_encoder_copy_buffer_to_buffer = wgpuCommandEncoderCopyBufferToBuffer(CommandEncoder, Buffer, UInt64, Buffer, UInt64, UInt64) : Void
  fun command_encoder_copy_buffer_to_texture = wgpuCommandEncoderCopyBufferToTexture(CommandEncoder, Pointer(TexelCopyBufferInfo), Pointer(TexelCopyTextureInfo), Pointer(Extent3D)) : Void
  fun command_encoder_copy_texture_to_buffer = wgpuCommandEncoderCopyTextureToBuffer(CommandEncoder, Pointer(TexelCopyTextureInfo), Pointer(TexelCopyBufferInfo), Pointer(Extent3D)) : Void
  fun command_encoder_copy_texture_to_texture = wgpuCommandEncoderCopyTextureToTexture(CommandEncoder, Pointer(TexelCopyTextureInfo), Pointer(TexelCopyTextureInfo), Pointer(Extent3D)) : Void
  fun command_encoder_finish = wgpuCommandEncoderFinish(CommandEncoder, Pointer(CommandBufferDescriptor)) : CommandBuffer
  fun command_encoder_insert_debug_marker = wgpuCommandEncoderInsertDebugMarker(CommandEncoder, StringView) : Void
  fun command_encoder_pop_debug_group = wgpuCommandEncoderPopDebugGroup(CommandEncoder) : Void
  fun command_encoder_push_debug_group = wgpuCommandEncoderPushDebugGroup(CommandEncoder, StringView) : Void
  fun command_encoder_resolve_query_set = wgpuCommandEncoderResolveQuerySet(CommandEncoder, QuerySet, UInt32, UInt32, Buffer, UInt64) : Void
  fun command_encoder_set_label = wgpuCommandEncoderSetLabel(CommandEncoder, StringView) : Void
  fun command_encoder_write_timestamp = wgpuCommandEncoderWriteTimestamp(CommandEncoder, QuerySet, UInt32) : Void
  fun command_encoder_add_ref = wgpuCommandEncoderAddRef(CommandEncoder) : Void
  fun command_encoder_release = wgpuCommandEncoderRelease(CommandEncoder) : Void
  fun compute_pass_encoder_dispatch_workgroups = wgpuComputePassEncoderDispatchWorkgroups(ComputePassEncoder, UInt32, UInt32, UInt32) : Void
  fun compute_pass_encoder_dispatch_workgroups_indirect = wgpuComputePassEncoderDispatchWorkgroupsIndirect(ComputePassEncoder, Buffer, UInt64) : Void
  fun compute_pass_encoder_end = wgpuComputePassEncoderEnd(ComputePassEncoder) : Void
  fun compute_pass_encoder_insert_debug_marker = wgpuComputePassEncoderInsertDebugMarker(ComputePassEncoder, StringView) : Void
  fun compute_pass_encoder_pop_debug_group = wgpuComputePassEncoderPopDebugGroup(ComputePassEncoder) : Void
  fun compute_pass_encoder_push_debug_group = wgpuComputePassEncoderPushDebugGroup(ComputePassEncoder, StringView) : Void
  fun compute_pass_encoder_set_bind_group = wgpuComputePassEncoderSetBindGroup(ComputePassEncoder, UInt32, BindGroup, LibC::SizeT, Pointer(UInt32)) : Void
  fun compute_pass_encoder_set_label = wgpuComputePassEncoderSetLabel(ComputePassEncoder, StringView) : Void
  fun compute_pass_encoder_set_pipeline = wgpuComputePassEncoderSetPipeline(ComputePassEncoder, ComputePipeline) : Void
  fun compute_pass_encoder_add_ref = wgpuComputePassEncoderAddRef(ComputePassEncoder) : Void
  fun compute_pass_encoder_release = wgpuComputePassEncoderRelease(ComputePassEncoder) : Void
  fun compute_pipeline_get_bind_group_layout = wgpuComputePipelineGetBindGroupLayout(ComputePipeline, UInt32) : BindGroupLayout
  fun compute_pipeline_set_label = wgpuComputePipelineSetLabel(ComputePipeline, StringView) : Void
  fun compute_pipeline_add_ref = wgpuComputePipelineAddRef(ComputePipeline) : Void
  fun compute_pipeline_release = wgpuComputePipelineRelease(ComputePipeline) : Void
  fun device_create_bind_group = wgpuDeviceCreateBindGroup(Device, Pointer(BindGroupDescriptor)) : BindGroup
  fun device_create_bind_group_layout = wgpuDeviceCreateBindGroupLayout(Device, Pointer(BindGroupLayoutDescriptor)) : BindGroupLayout
  fun device_create_buffer = wgpuDeviceCreateBuffer(Device, Pointer(BufferDescriptor)) : Buffer
  fun device_create_command_encoder = wgpuDeviceCreateCommandEncoder(Device, Pointer(CommandEncoderDescriptor)) : CommandEncoder
  fun device_create_compute_pipeline = wgpuDeviceCreateComputePipeline(Device, Pointer(ComputePipelineDescriptor)) : ComputePipeline
  fun device_create_compute_pipeline_async = wgpuDeviceCreateComputePipelineAsync(Device, Pointer(ComputePipelineDescriptor), CreateComputePipelineAsyncCallbackInfo) : Future
  fun device_create_pipeline_layout = wgpuDeviceCreatePipelineLayout(Device, Pointer(PipelineLayoutDescriptor)) : PipelineLayout
  fun device_create_query_set = wgpuDeviceCreateQuerySet(Device, Pointer(QuerySetDescriptor)) : QuerySet
  fun device_create_render_bundle_encoder = wgpuDeviceCreateRenderBundleEncoder(Device, Pointer(RenderBundleEncoderDescriptor)) : RenderBundleEncoder
  fun device_create_render_pipeline = wgpuDeviceCreateRenderPipeline(Device, Pointer(RenderPipelineDescriptor)) : RenderPipeline
  fun device_create_render_pipeline_async = wgpuDeviceCreateRenderPipelineAsync(Device, Pointer(RenderPipelineDescriptor), CreateRenderPipelineAsyncCallbackInfo) : Future
  fun device_create_sampler = wgpuDeviceCreateSampler(Device, Pointer(SamplerDescriptor)) : Sampler
  fun device_create_shader_module = wgpuDeviceCreateShaderModule(Device, Pointer(ShaderModuleDescriptor)) : ShaderModule
  fun device_create_texture = wgpuDeviceCreateTexture(Device, Pointer(TextureDescriptor)) : Texture
  fun device_destroy = wgpuDeviceDestroy(Device) : Void
  fun device_get_adapter_info = wgpuDeviceGetAdapterInfo(Device, Pointer(AdapterInfo)) : Status
  fun device_get_features = wgpuDeviceGetFeatures(Device, Pointer(SupportedFeatures)) : Void
  fun device_get_limits = wgpuDeviceGetLimits(Device, Pointer(Limits)) : Status
  fun device_get_lost_future = wgpuDeviceGetLostFuture(Device) : Future
  fun device_get_queue = wgpuDeviceGetQueue(Device) : Queue
  fun device_has_feature = wgpuDeviceHasFeature(Device, FeatureName) : Bool
  fun device_pop_error_scope = wgpuDevicePopErrorScope(Device, PopErrorScopeCallbackInfo) : Future
  fun device_push_error_scope = wgpuDevicePushErrorScope(Device, ErrorFilter) : Void
  fun device_set_label = wgpuDeviceSetLabel(Device, StringView) : Void
  fun device_add_ref = wgpuDeviceAddRef(Device) : Void
  fun device_release = wgpuDeviceRelease(Device) : Void
  fun external_texture_set_label = wgpuExternalTextureSetLabel(ExternalTexture, StringView) : Void
  fun external_texture_add_ref = wgpuExternalTextureAddRef(ExternalTexture) : Void
  fun external_texture_release = wgpuExternalTextureRelease(ExternalTexture) : Void
  fun instance_create_surface = wgpuInstanceCreateSurface(Instance, Pointer(SurfaceDescriptor)) : Surface
  fun instance_get_wgsl_language_features = wgpuInstanceGetWGSLLanguageFeatures(Instance, Pointer(SupportedWGSLLanguageFeatures)) : Void
  fun instance_has_wgsl_language_feature = wgpuInstanceHasWGSLLanguageFeature(Instance, WGSLLanguageFeatureName) : Bool
  fun instance_process_events = wgpuInstanceProcessEvents(Instance) : Void
  fun instance_request_adapter = wgpuInstanceRequestAdapter(Instance, Pointer(RequestAdapterOptions), RequestAdapterCallbackInfo) : Future
  fun instance_wait_any = wgpuInstanceWaitAny(Instance, LibC::SizeT, Pointer(FutureWaitInfo), UInt64) : WaitStatus
  fun instance_add_ref = wgpuInstanceAddRef(Instance) : Void
  fun instance_release = wgpuInstanceRelease(Instance) : Void
  fun pipeline_layout_set_label = wgpuPipelineLayoutSetLabel(PipelineLayout, StringView) : Void
  fun pipeline_layout_add_ref = wgpuPipelineLayoutAddRef(PipelineLayout) : Void
  fun pipeline_layout_release = wgpuPipelineLayoutRelease(PipelineLayout) : Void
  fun query_set_destroy = wgpuQuerySetDestroy(QuerySet) : Void
  fun query_set_get_count = wgpuQuerySetGetCount(QuerySet) : UInt32
  fun query_set_get_type = wgpuQuerySetGetType(QuerySet) : QueryType
  fun query_set_set_label = wgpuQuerySetSetLabel(QuerySet, StringView) : Void
  fun query_set_add_ref = wgpuQuerySetAddRef(QuerySet) : Void
  fun query_set_release = wgpuQuerySetRelease(QuerySet) : Void
  fun queue_on_submitted_work_done = wgpuQueueOnSubmittedWorkDone(Queue, QueueWorkDoneCallbackInfo) : Future
  fun queue_set_label = wgpuQueueSetLabel(Queue, StringView) : Void
  fun queue_submit = wgpuQueueSubmit(Queue, LibC::SizeT, Pointer(CommandBuffer)) : Void
  fun queue_write_buffer = wgpuQueueWriteBuffer(Queue, Buffer, UInt64, Pointer(Void), LibC::SizeT) : Void
  fun queue_write_texture = wgpuQueueWriteTexture(Queue, Pointer(TexelCopyTextureInfo), Pointer(Void), LibC::SizeT, Pointer(TexelCopyBufferLayout), Pointer(Extent3D)) : Void
  fun queue_add_ref = wgpuQueueAddRef(Queue) : Void
  fun queue_release = wgpuQueueRelease(Queue) : Void
  fun render_bundle_set_label = wgpuRenderBundleSetLabel(RenderBundle, StringView) : Void
  fun render_bundle_add_ref = wgpuRenderBundleAddRef(RenderBundle) : Void
  fun render_bundle_release = wgpuRenderBundleRelease(RenderBundle) : Void
  fun render_bundle_encoder_draw = wgpuRenderBundleEncoderDraw(RenderBundleEncoder, UInt32, UInt32, UInt32, UInt32) : Void
  fun render_bundle_encoder_draw_indexed = wgpuRenderBundleEncoderDrawIndexed(RenderBundleEncoder, UInt32, UInt32, UInt32, Int32, UInt32) : Void
  fun render_bundle_encoder_draw_indexed_indirect = wgpuRenderBundleEncoderDrawIndexedIndirect(RenderBundleEncoder, Buffer, UInt64) : Void
  fun render_bundle_encoder_draw_indirect = wgpuRenderBundleEncoderDrawIndirect(RenderBundleEncoder, Buffer, UInt64) : Void
  fun render_bundle_encoder_finish = wgpuRenderBundleEncoderFinish(RenderBundleEncoder, Pointer(RenderBundleDescriptor)) : RenderBundle
  fun render_bundle_encoder_insert_debug_marker = wgpuRenderBundleEncoderInsertDebugMarker(RenderBundleEncoder, StringView) : Void
  fun render_bundle_encoder_pop_debug_group = wgpuRenderBundleEncoderPopDebugGroup(RenderBundleEncoder) : Void
  fun render_bundle_encoder_push_debug_group = wgpuRenderBundleEncoderPushDebugGroup(RenderBundleEncoder, StringView) : Void
  fun render_bundle_encoder_set_bind_group = wgpuRenderBundleEncoderSetBindGroup(RenderBundleEncoder, UInt32, BindGroup, LibC::SizeT, Pointer(UInt32)) : Void
  fun render_bundle_encoder_set_index_buffer = wgpuRenderBundleEncoderSetIndexBuffer(RenderBundleEncoder, Buffer, IndexFormat, UInt64, UInt64) : Void
  fun render_bundle_encoder_set_label = wgpuRenderBundleEncoderSetLabel(RenderBundleEncoder, StringView) : Void
  fun render_bundle_encoder_set_pipeline = wgpuRenderBundleEncoderSetPipeline(RenderBundleEncoder, RenderPipeline) : Void
  fun render_bundle_encoder_set_vertex_buffer = wgpuRenderBundleEncoderSetVertexBuffer(RenderBundleEncoder, UInt32, Buffer, UInt64, UInt64) : Void
  fun render_bundle_encoder_add_ref = wgpuRenderBundleEncoderAddRef(RenderBundleEncoder) : Void
  fun render_bundle_encoder_release = wgpuRenderBundleEncoderRelease(RenderBundleEncoder) : Void
  fun render_pass_encoder_begin_occlusion_query = wgpuRenderPassEncoderBeginOcclusionQuery(RenderPassEncoder, UInt32) : Void
  fun render_pass_encoder_draw = wgpuRenderPassEncoderDraw(RenderPassEncoder, UInt32, UInt32, UInt32, UInt32) : Void
  fun render_pass_encoder_draw_indexed = wgpuRenderPassEncoderDrawIndexed(RenderPassEncoder, UInt32, UInt32, UInt32, Int32, UInt32) : Void
  fun render_pass_encoder_draw_indexed_indirect = wgpuRenderPassEncoderDrawIndexedIndirect(RenderPassEncoder, Buffer, UInt64) : Void
  fun render_pass_encoder_draw_indirect = wgpuRenderPassEncoderDrawIndirect(RenderPassEncoder, Buffer, UInt64) : Void
  fun render_pass_encoder_end = wgpuRenderPassEncoderEnd(RenderPassEncoder) : Void
  fun render_pass_encoder_end_occlusion_query = wgpuRenderPassEncoderEndOcclusionQuery(RenderPassEncoder) : Void
  fun render_pass_encoder_execute_bundles = wgpuRenderPassEncoderExecuteBundles(RenderPassEncoder, LibC::SizeT, Pointer(RenderBundle)) : Void
  fun render_pass_encoder_insert_debug_marker = wgpuRenderPassEncoderInsertDebugMarker(RenderPassEncoder, StringView) : Void
  fun render_pass_encoder_pop_debug_group = wgpuRenderPassEncoderPopDebugGroup(RenderPassEncoder) : Void
  fun render_pass_encoder_push_debug_group = wgpuRenderPassEncoderPushDebugGroup(RenderPassEncoder, StringView) : Void
  fun render_pass_encoder_set_bind_group = wgpuRenderPassEncoderSetBindGroup(RenderPassEncoder, UInt32, BindGroup, LibC::SizeT, Pointer(UInt32)) : Void
  fun render_pass_encoder_set_blend_constant = wgpuRenderPassEncoderSetBlendConstant(RenderPassEncoder, Pointer(Color)) : Void
  fun render_pass_encoder_set_index_buffer = wgpuRenderPassEncoderSetIndexBuffer(RenderPassEncoder, Buffer, IndexFormat, UInt64, UInt64) : Void
  fun render_pass_encoder_set_label = wgpuRenderPassEncoderSetLabel(RenderPassEncoder, StringView) : Void
  fun render_pass_encoder_set_pipeline = wgpuRenderPassEncoderSetPipeline(RenderPassEncoder, RenderPipeline) : Void
  fun render_pass_encoder_set_scissor_rect = wgpuRenderPassEncoderSetScissorRect(RenderPassEncoder, UInt32, UInt32, UInt32, UInt32) : Void
  fun render_pass_encoder_set_stencil_reference = wgpuRenderPassEncoderSetStencilReference(RenderPassEncoder, UInt32) : Void
  fun render_pass_encoder_set_vertex_buffer = wgpuRenderPassEncoderSetVertexBuffer(RenderPassEncoder, UInt32, Buffer, UInt64, UInt64) : Void
  fun render_pass_encoder_set_viewport = wgpuRenderPassEncoderSetViewport(RenderPassEncoder, Float32, Float32, Float32, Float32, Float32, Float32) : Void
  fun render_pass_encoder_add_ref = wgpuRenderPassEncoderAddRef(RenderPassEncoder) : Void
  fun render_pass_encoder_release = wgpuRenderPassEncoderRelease(RenderPassEncoder) : Void
  fun render_pipeline_get_bind_group_layout = wgpuRenderPipelineGetBindGroupLayout(RenderPipeline, UInt32) : BindGroupLayout
  fun render_pipeline_set_label = wgpuRenderPipelineSetLabel(RenderPipeline, StringView) : Void
  fun render_pipeline_add_ref = wgpuRenderPipelineAddRef(RenderPipeline) : Void
  fun render_pipeline_release = wgpuRenderPipelineRelease(RenderPipeline) : Void
  fun sampler_set_label = wgpuSamplerSetLabel(Sampler, StringView) : Void
  fun sampler_add_ref = wgpuSamplerAddRef(Sampler) : Void
  fun sampler_release = wgpuSamplerRelease(Sampler) : Void
  fun shader_module_get_compilation_info = wgpuShaderModuleGetCompilationInfo(ShaderModule, CompilationInfoCallbackInfo) : Future
  fun shader_module_set_label = wgpuShaderModuleSetLabel(ShaderModule, StringView) : Void
  fun shader_module_add_ref = wgpuShaderModuleAddRef(ShaderModule) : Void
  fun shader_module_release = wgpuShaderModuleRelease(ShaderModule) : Void
  fun supported_features_free_members = wgpuSupportedFeaturesFreeMembers(SupportedFeatures) : Void
  fun supported_instance_features_free_members = wgpuSupportedInstanceFeaturesFreeMembers(SupportedInstanceFeatures) : Void
  fun supported_wgsl_language_features_free_members = wgpuSupportedWGSLLanguageFeaturesFreeMembers(SupportedWGSLLanguageFeatures) : Void
  fun surface_configure = wgpuSurfaceConfigure(Surface, Pointer(SurfaceConfiguration)) : Void
  fun surface_get_capabilities = wgpuSurfaceGetCapabilities(Surface, Adapter, Pointer(SurfaceCapabilities)) : Status
  fun surface_get_current_texture = wgpuSurfaceGetCurrentTexture(Surface, Pointer(SurfaceTexture)) : Void
  fun surface_present = wgpuSurfacePresent(Surface) : Status
  fun surface_set_label = wgpuSurfaceSetLabel(Surface, StringView) : Void
  fun surface_unconfigure = wgpuSurfaceUnconfigure(Surface) : Void
  fun surface_add_ref = wgpuSurfaceAddRef(Surface) : Void
  fun surface_release = wgpuSurfaceRelease(Surface) : Void
  fun surface_capabilities_free_members = wgpuSurfaceCapabilitiesFreeMembers(SurfaceCapabilities) : Void
  fun texture_create_view = wgpuTextureCreateView(Texture, Pointer(TextureViewDescriptor)) : TextureView
  fun texture_destroy = wgpuTextureDestroy(Texture) : Void
  fun texture_get_depth_or_array_layers = wgpuTextureGetDepthOrArrayLayers(Texture) : UInt32
  fun texture_get_dimension = wgpuTextureGetDimension(Texture) : TextureDimension
  fun texture_get_format = wgpuTextureGetFormat(Texture) : TextureFormat
  fun texture_get_height = wgpuTextureGetHeight(Texture) : UInt32
  fun texture_get_mip_level_count = wgpuTextureGetMipLevelCount(Texture) : UInt32
  fun texture_get_sample_count = wgpuTextureGetSampleCount(Texture) : UInt32
  fun texture_get_texture_binding_view_dimension = wgpuTextureGetTextureBindingViewDimension(Texture) : TextureViewDimension
  fun texture_get_usage = wgpuTextureGetUsage(Texture) : TextureUsage
  fun texture_get_width = wgpuTextureGetWidth(Texture) : UInt32
  fun texture_set_label = wgpuTextureSetLabel(Texture, StringView) : Void
  fun texture_add_ref = wgpuTextureAddRef(Texture) : Void
  fun texture_release = wgpuTextureRelease(Texture) : Void
  fun texture_view_set_label = wgpuTextureViewSetLabel(TextureView, StringView) : Void
  fun texture_view_add_ref = wgpuTextureViewAddRef(TextureView) : Void
  fun texture_view_release = wgpuTextureViewRelease(TextureView) : Void
end
