#!/usr/bin/env bash
#
# Downloads wgpu-native (https://github.com/gfx-rs/wgpu-native) and installs
# the library, the C headers and the webgpu.yml spec into vendor/wgpu-native/.
#
# Usage:
#   scripts/download_wgpu.sh [version]
#
# Environment variables:
#   WGPU_NATIVE_VERSION   version to install (e.g. v29.0.0.0). Default: latest release.
#   WGPU_NATIVE_BUILD     "release" (default) or "debug".
#   WGPU_NATIVE_OS        force OS  : macos | linux | windows.
#   WGPU_NATIVE_ARCH      force arch: aarch64 | x86_64 | i686.
#
set -euo pipefail

REPO="gfx-rs/wgpu-native"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
DEST="${ROOT_DIR}/vendor/wgpu-native"

BUILD="${WGPU_NATIVE_BUILD:-release}"

log()  { printf '\033[1;34m==>\033[0m %s\n' "$*" >&2; }
err()  { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# OS / architecture detection
# ---------------------------------------------------------------------------
detect_os() {
  if [ -n "${WGPU_NATIVE_OS:-}" ]; then echo "${WGPU_NATIVE_OS}"; return; fi
  case "$(uname -s)" in
    Darwin)              echo macos ;;
    Linux)               echo linux ;;
    MINGW*|MSYS*|CYGWIN*) echo windows ;;
    *) err "unsupported OS: $(uname -s)" ;;
  esac
}

detect_arch() {
  if [ -n "${WGPU_NATIVE_ARCH:-}" ]; then echo "${WGPU_NATIVE_ARCH}"; return; fi
  case "$(uname -m)" in
    arm64|aarch64) echo aarch64 ;;
    x86_64|amd64)  echo x86_64 ;;
    i386|i686)     echo i686 ;;
    *) err "unsupported architecture: $(uname -m)" ;;
  esac
}

OS="$(detect_os)"
ARCH="$(detect_arch)"

# Windows-specific asset suffix (msvc ABI by default).
asset_name() {
  case "${OS}" in
    windows) echo "wgpu-windows-${ARCH}-msvc-${BUILD}.zip" ;;
    *)       echo "wgpu-${OS}-${ARCH}-${BUILD}.zip" ;;
  esac
}

# ---------------------------------------------------------------------------
# Version resolution
# ---------------------------------------------------------------------------
resolve_version() {
  local v="${1:-${WGPU_NATIVE_VERSION:-}}"
  if [ -n "${v}" ] && [ "${v}" != "latest" ]; then
    echo "${v}"; return
  fi
  log "Resolving the latest release of ${REPO}…"
  local json tag
  json="$(curl -fsSL "https://api.github.com/repos/${REPO}/releases/latest")"
  tag="$(printf '%s' "${json}" | grep '"tag_name":' | head -n1 \
          | sed -E 's/.*"tag_name": *"([^"]+)".*/\1/')"
  [ -n "${tag}" ] || err "Could not resolve the latest version (GitHub API rate limit?). Pass a version as an argument."
  echo "${tag}"
}

VERSION="$(resolve_version "${1:-}")"
ASSET="$(asset_name)"
URL="https://github.com/${REPO}/releases/download/${VERSION}/${ASSET}"

# ---------------------------------------------------------------------------
# Download + extraction
# ---------------------------------------------------------------------------
log "Platform : ${OS}/${ARCH} (${BUILD})"
log "Version  : ${VERSION}"
log "Asset    : ${ASSET}"

TMP="$(mktemp -d)"
trap 'rm -rf "${TMP}"' EXIT

log "Downloading ${URL}"
curl -fSL --progress-bar -o "${TMP}/wgpu.zip" "${URL}" \
  || err "download failed (does version ${VERSION} exist for ${OS}/${ARCH}?)"

log "Extracting…"
unzip -q "${TMP}/wgpu.zip" -d "${TMP}/extract"

rm -rf "${DEST}"
mkdir -p "${DEST}"
# The zip layout is: include/  lib/  wgpu-native-meta/
cp -R "${TMP}/extract/." "${DEST}/"

printf '%s' "${VERSION}" > "${DEST}/VERSION"

log "Installed into ${DEST}"
ls -1 "${DEST}/lib" 2>/dev/null | sed 's/^/    lib\//' >&2 || true

# ---------------------------------------------------------------------------
# Generate link flags (absolute paths -> `crystal run` works without
# configuring LIBRARY_PATH / DYLD_LIBRARY_PATH).
# ---------------------------------------------------------------------------
LINK_FILE="${ROOT_DIR}/src/wgpu/link.cr"
mkdir -p "$(dirname "${LINK_FILE}")"

case "${OS}" in
  macos)
    # -fuse-ld=/usr/bin/ld : force Apple's linker. Some Homebrew installs ship
    # an lld whose version does not match libLLVM, which breaks Crystal's
    # default link. The system linker is safe.
    LDFLAGS="-fuse-ld=/usr/bin/ld -L${DEST}/lib -lwgpu_native -Wl,-rpath,${DEST}/lib"
    ;;
  linux)
    LDFLAGS="-L${DEST}/lib -lwgpu_native -Wl,-rpath,${DEST}/lib"
    ;;
  windows)
    LDFLAGS="-L${DEST}/lib -lwgpu_native"
    ;;
esac

cat > "${LINK_FILE}" <<EOF
# Generated by scripts/download_wgpu.sh — DO NOT edit by hand.
# wgpu-native ${VERSION} (${OS}/${ARCH}, ${BUILD})
@[Link(ldflags: "${LDFLAGS}")]
lib LibWGPU
end
EOF

log "Link flags written to src/wgpu/link.cr"
log "Done. Next step: crystal run scripts/generate_bindings.cr"
